### ISSUE TITLE
Remove background - onnx-community/BEN2-ONNX - bug when using webGPU

### ISSUE THREAD

**Issue by pikilipita** [huggingface/transformers.js#1272]
### System Info

transformers 3.4.1
macOs 14.7.4
Chrome 136

### Environment/Platform

- [x] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

While using onnx-community/BEN2-ONNX to remove background, the wasm version result is fine, but the webGPU result adds a 'ghost' on the mask:

<img width="503" alt="Image" src="https://github.com/user-attachments/assets/ce1787e1-0501-4832-a930-a246fb42eca8" />

the original image of this example be found here, but the ghosting issue is happening on all images I tested.
[https://unsplash.com/photos/woman-standing-near-pink-concrete-wall-during-daytime-TT-ROxWj9nA](url)

tested on transformers 3.4.1 with those settings:

`var segmenter = await pipeline("background-removal", "onnx-community/BEN2-ONNX", {
    device:"webgpu"
});`

### Reproduction

to reproduce, use those settings with any input image:
`var segmenter = await pipeline("background-removal", "onnx-community/BEN2-ONNX", {
    device:"webgpu"
});`

**Comment by xenova** [comment]
cc @fs-eire in case you have any ideas.

**Comment by prathikr** [comment]
Looking into the issue...

**Comment by prathikr** [comment]
Hi @pikilipita do you have a full index.html that reproduces this issue? Something that generates the binary image and displays it on the page?

**Comment by pikilipita** [comment]
@prathikr 
yes, I just made one for you:
[https://pikimov.com/tr-test/](https://pikimov.com/tr-test/)

**Comment by prathikr** [comment]
Hi @pikilipita, thank you for your patience. @fs-eire and I looked at your model and noticed a peculiar pattern. In both the multifieldcrossatt and dec_blk modules there is a softmax that feeds to a cast-to-fp32 followed by a cast-to-fp16:
![Image](https://github.com/user-attachments/assets/ccf230bb-e8af-4ae1-8ba7-308a45f01eee)
If I adjust it to follow the pattern cast-to-fp32 --> softmax --> cast-to-fp16 then the model works:
![Image](https://github.com/user-attachments/assets/a5fbc746-39da-45a3-b35b-f5525a0d2287)

Can you please double check how the multifieldcrossatt and dec_blk modules are implemented to see if the second pattern can be followed?

**Comment by xenova** [comment]
It's using the float16 quantization script: https://github.com/huggingface/transformers.js/blob/main/scripts/float16.py, which is adapted from a bunch of other scripts.

I'm pretty certain the bug is from there, for when there is already an existing cast node in the graph.

Would greatly appreciate help in fixing it @prathikr if you have time.

**Comment by prathikr** [comment]
@xenova do you use BEN2_Base.onnx as input to this script? I can see the softmax --> cast to fp32 --> cast to fp16 is in the base model so this script may not be the issue. It is likely an issue in the original model implementation. I have a version of onnx-community/BEN2-ONNX with the swapped nodes I can email if that would help.

**Comment by prathikr** [comment]
https://huggingface.co/onnx-community/BEN2-ONNX/discussions/2

**Comment by xenova** [comment]
Thanks to @prathikr, this is now fixed :) (make sure to clear your browser cache to test)

Turns out, as he points out, it was an issue with the original model, not the conversion script, and the fp32 -> fp16 -> softmax pattern was the root of the problem.

**Comment by pikilipita** [comment]
I still have the exact same ghost bug with webGPU on the demo I shared few weeks ago ( [https://pikimov.com/tr-test/](https://pikimov.com/tr-test/) ) even after clearing the cache ( macOS, chrome 137) , do I need to change some settings?

**Comment by xenova** [comment]
It's a different kind of cache: you need to open dev tools -> Application -> Cache storage -> right click and delete `transformers-cache`

You will then get:

<img width="487" alt="Image" src="https://github.com/user-attachments/assets/e195603e-509b-4e90-ae3c-816c09394cf8" />

you can also test it out by opening an incognito tab

**Comment by pikilipita** [comment]
Thank you very much, that worked, and indeed the ghosting issue is gone
