### ISSUE TITLE
Embeddings generated different between js and python for some models

### ISSUE THREAD

**Issue by ashikns** [huggingface/transformers.js#1331]
### System Info

Windows 11 22631.5335

transformers.js 3.5.2
React 19

python 3.12
transformers 4.52.4
optimum 1.17.1
onnxruntime 1.22.0

All dependencies pinned in linked sample project.

### Environment/Platform

- [x] Website/web-app
- [ ] Browser extension
- [x] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Set 1 embeddings: generated in browser using fp16, webgpu
Set 2 embeddings: generated in python using ORTModelForFeatureExtraction, file_name=model_fp16.onnx

When using the model https://huggingface.co/Xenova/all-MiniLM-L6-v2 it works as expected. Cosine similarity between embeddings generated in js and python is >0.99.

However when using the model https://huggingface.co/Xenova/e5-base-v2 the embeddings differ by a significant amount. Cosine similarity is ~0.75.

Since onnx models are used in both environments and it works for the more popular model, I felt like this might be a bug and not a quantization issue.

### Reproduction

I have a sample project setup to demonstrate this: https://github.com/ashikns/embedding-compare.

README of project describes steps to run (just two barebone folders). It uses `Xenova/e5-base-v2`, but also works with `Xenova/all-MiniLM-L6-v2`.

**Comment by xenova** [comment]
Hi there 👋  Could you try `device: "wasm"` to see if it's an issue with webgpu?

**Comment by SignOfZeta** [comment]
> Hi there 👋 Could you try `device: "wasm"` to see if it's an issue with webgpu?

I have tested the sample code by @ashikns.

`Xenova/e5-base-v2` fp16 gives a cosine similarity of ~0.74 between JavaScript WebGPU and Python; 1.00 between JavaScript WebAssembly and Python, which matches ashikns' description.
Here are the result embeddings:
[embedding_wasm_fp16.json](https://github.com/user-attachments/files/20582711/embedding_wasm_fp16.json)
[embedding_webgpu_fp16.json](https://github.com/user-attachments/files/20582712/embedding_webgpu_fp16.json)

Additionally, I tested `Xenova/e5-base-v2` q8. It gives a cosine similarity of ~0.64 between JavaScript WebGPU and Python; >0.99 between JavaScript WebAssembly and Python.
Here are the result embeddings:
[embedding_wasm_q8.json](https://github.com/user-attachments/files/20582639/embedding_wasm_q8.json)
[embedding_webgpu_q8.json](https://github.com/user-attachments/files/20582641/embedding_webgpu_q8.json)

Lastly, I tested `Xenova/e5-base-v2` fp32. It gives a cosine similarity of 1.00 between JavaScript WebGPU and Python; 1.00 between JavaScript WebAssembly and Python.
Here are the result embeddings:
[embedding_wasm_fp32.json](https://github.com/user-attachments/files/20582733/embedding_wasm_fp32.json)
[embedding_webgpu_fp32.json](https://github.com/user-attachments/files/20582734/embedding_webgpu_fp32.json)

The difference between fp32 result and fp16/q8 results suggests that the ONNX converted models are quantized properly, I think @xenova's assumption in [#1317/Comment](https://github.com/huggingface/transformers.js/issues/1317#issuecomment-2914190176) about dequantizing error was correct.

**Comment by ashikns** [comment]
I confirmed on my end as well. Generating with `device: wasm, dtype: fp16` gave embeddings that are 1.00 similarity with python. It does seem like an issue with webgpu.

**Comment by mahdin75** [comment]
Hey, 
The same issue #1379 . However, in my case, I am using a custom model based on T5-small. 
```
{
     dtype: "fp32",
     device: "wasm",
 }

```

Could anyone help me fix this difference?

**Comment by xenova** [comment]
Hi again 👋 This has now been fixed with Transformers.js V4: https://github.com/huggingface/transformers.js/pull/1382.

You can test it out by installing it via
```sh
npm i @huggingface/transformers@next
```

Feel free to re-open if you run into any issues or have any questions.

**Comment by Lapis0x0** [comment]
Reopening consideration: **the fp16 + WebGPU deviation still reproduces on v4.2.0** (the q8 case does appear fixed).

Setup: `Xenova/bge-small-en-v1.5`, transformers.js 4.2.0 / onnxruntime-web 1.26.0-dev.20260416, Electron (Obsidian) on macOS. Taking fp32 weights on CPU as ground truth:

| config | cosine vs fp32 truth |
|---|---|
| wasm + q8 | 0.993 – 0.997 ✅ |
| webgpu + q8 | matches CPU q8 ✅ (fixed in V4) |
| **webgpu + fp16** | **0.49 – 0.71** ❌ |
| webgpu + q4f16 | ~0.60 ❌ |

The weight files are not at fault: the **same** `model_fp16.onnx` on Python onnxruntime 1.29.0 (CPU EP) is bit-identical to fp32 truth (cosine 0.999999+), and q4f16 shows only normal quantization noise there (0.973–0.990).

Notably the WebGPU fp16 outputs are *finite, norm-1 and internally self-consistent* — just living in a shifted space (e.g. cat~kitten: 0.8659 fp32 truth → 0.8271 webgpu fp16). This "silently wrong rather than obviously broken" signature matches microsoft/onnxruntime#31626 (fp16 overflow in a decomposed LayerNorm, Inf variance absorbed by the Div). Circumstantial support: this export does contain the decomposed LayerNorm pattern — loading the same fp16 file on ort-web 1.26's **CPU** EP crashes inside `SimplifiedLayerNormFusion` (`GetIndexFromName` assertion).

Happy to provide a minimal repro or more measurements if useful. Should this be reopened here, or filed against onnxruntime directly?
